language: generic

stages:
  - name: push
    if: fork = false AND branch = master

jobs:
  include:
    - stage: push
      script:
        - cd $HOME/gopath/src/github.com/integr8ly/manifests
        - make push/all QUAY_USERNAME="${QUAY_USERNAME}" QUAY_PASSWORD="${QUAY_PASSWORD}" REPO="integreatly"
